name: Context testing
on: 
  push:
    paths:
      - '.github/workflows/expression.yml' 

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        if: success()
        run: eccho '${{ toJSON(job) }}'
      - name: Dump steps context
        if: failure()
        run: eccho '${{ toJSON(steps) }}'
      - name: Dump runner context
        if: always()
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        if: cancelled()
        run: echo '${{ toJSON(matrix) }}'
  functions_expression:
    runs-on: ubuntu-latest
    needs: [dump_contexts_to_log]
    steps:
      - name: functions
        run: |
          echo ${{ contains('hello','ll') }}
          echo ${{ startsWith('hello','he') }}
          echo ${{ endsWith('hello','lo') }}
          echo ${{ format('Hello {0} {1}','World','!') }}