name: github actions workflow
on: [push, pull_request]
#env:

jobs:
  first_job:
    name: first_job
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.env}}
      output2: ${{steps.step2.outputs.env}}
    steps:
      - id: one
        name: print envs
        run: printenv
      - id: two
        name: echo
        run: echo "Hi there"

  second_job:
    name: second job
    runs-on: ubuntu-latest
    steps:
      - name: run python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  third_job:
    name: third job
    runs-on: windows-latest
    steps:
      - name: run python command
        run: |
          import platform
          print(platform.processor())
        shell: python
      - name: run bash command
        run: |
          pwd
        shell: bash
      - name: run python command
        run: |
          get-command
  # second_job:
  #   name: second_job
  #   runs-on: ubuntu-latest
  #   needs: first_job
  #   strategy:
  #     matrix:
  #       environment: ['${{needs.first_job.outputs.output1}}','${{needs.first_job.outputs.output2}}']
  #       exclude: 
  #         - environment: ''
  #   environment: ${{matrix.environment}}
  #   steps:
  #     - id: one
  #       name: print output of first job
  #       run: echo $environment
