name: Trigger Action
on: 
  # schedule:
  #   - cron: "0/5 * * * *"

  repository_dispatch:
    types: [test_result]
  

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: verify checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{ github.event.repository.name }}
          echo ${{ github.event.client_payload.message}}